### ISSUE TITLE
자세한 신청 방법 추가

### ISSUE THREAD

**Issue by IsotropicUniverse** [sonjun/KNU_CSE#1]
표에 있는 항목들을 누르면 자세한 신청 방법을 설명해주면 좋을 것 같네요. 현재 포크해서 작업중이니 나중에 PR 넣겠습니다.

**Comment by IsotropicUniverse** [comment]
**완료**. [Pull request](https://github.com/jun-2525/KNU_CSE/pull/2) 확인하세요.

**Comment by jun-2525** [comment]
확인 후 marge 했습니다
